# Generated by Django 3.2.6 on 2021-10-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20211011_1318'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente_sistema',
        ),
    ]
