# Generated by Django 3.2.6 on 2021-10-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-data_nascimento']},
        ),
    ]
