# Generated by Django 3.2.6 on 2021-10-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_blog', '0003_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='pais_origm',
            new_name='pais_origem',
        ),
    ]
