# Generated by Django 3.2.6 on 2021-10-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_blog', '0007_auto_20211018_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capa',
            field=models.ImageField(null=True, upload_to='artigos/'),
        ),
    ]
