# Generated by Django 3.2.6 on 2021-10-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
