# Generated by Django 3.2.6 on 2021-10-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tecnologia_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='tipo_contrataco',
            new_name='tipo_contratacao',
        ),
    ]
